services:
  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./frontend:/app
    networks:
      - filkx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auction-frontend.rule=Host(`dev.auction.filkx.com`)"
      - "traefik.http.routers.auction-frontend.entrypoints=websecure"
      - "traefik.http.routers.auction-frontend.tls.certresolver=devresolver"
      - "traefik.http.services.auction-frontend.loadbalancer.server.port=80"

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm
    networks:
      - filkx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auction-api.rule=Host(`dev.api.auction.filkx.com`)"
      - "traefik.http.routers.auction-api.entrypoints=websecure"
      - "traefik.http.routers.auction-api.tls.certresolver=devresolver"
      - "traefik.http.services.auction-api.loadbalancer.server.port=80"

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./api:/app
    networks:
      - filkx

  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    user: "1000:1000"
    volumes:
      - ./api:/app
    networks:
      - filkx

  api-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: auction
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: auction
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - filkx

networks:
  filkx:
    external: true

volumes:
  api-postgres:
